FROM nginx:alpine

COPY ./client/sender.html /usr/share/nginx/html/sender.html
COPY ./client/receiver.html /usr/share/nginx/html/receiver.html
COPY ./client/history.html /usr/share/nginx/html/history.html

EXPOSE 80
